### ISSUE TITLE
error running morfee.annotation()

### ISSUE THREAD

**Issue by ElenaBiagi** [daissi/MORFEE#4]
Greetings, 

I am trying to run MORFEE on a previously Annovar-annotated vcf, here named ``` "my_vcf" ```.
I followed the instructions in the README.md, but when reaching the following command 
```{r}
morfee.annotation(my_vcf, MORFEE_DATA)
```
I got this error message ```Error in normalizeDoubleBracketSubscript(i, x, exact = exact, allow.NA = TRUE,  : subscript is out of bounds``` and the execution stops after 15749 variants.

Please let me know how i could fix this error.

Thanks in advance !

**Comment by daissi** [comment]
Hi,

It looks like an issue with a dependency of MORFEE.
Could you send me a minimal anonymized dataset to reproduce this issue?
I guess there is an issue with variant 15750, so a vcf with variants from 15745 to 15755 should be fine.

Best,
Dylan

**Comment by ElenaBiagi** [comment]
Thank you very much for your celerity in answering. 
I have already tried removing the variant 15750, but the problem remained the same. I thought it could be due to an issue with the variant 15751 as well. 
I'll try to reduce the file and I will send it to you as soon as possible.

Thanks again
